[package]
name = "read_csv"
version = "0.1.0"
authors = ["bell liang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2"
structopt-derive = "0.2"
